[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."getMessage"]
  timeout = 30

[[redirects]]
  from = "/api/getMessage"
  to = "/.netlify/functions/getMessage"
  status = 200
